SB_CONFIG_SECURE_BOOT_APPCORE=y
SB_CONFIG_SECURE_BOOT_SIGNING_KEY_FILE="/opt/nordic/ncs/v3.1.1/bootloader/mcuboot/root-ec-p256.pem"
SB_CONFIG_BOOTLOADER_MCUBOOT=y
SB_CONFIG_BOOT_SIGNATURE_TYPE_ECDSA_P256=y
SB_CONFIG_BOOT_SIGNATURE_KEY_FILE="/opt/nordic/ncs/v3.1.1/bootloader/mcuboot/root-ec-p256.pem"